# Door 3: nada em src/core pode incluir raylib.h.
file(GLOB_RECURSE core_files "${CORE_DIR}/*.c" "${CORE_DIR}/*.h")
list(LENGTH core_files n)
if(n EQUAL 0)
  message(FATAL_ERROR "nenhum arquivo em ${CORE_DIR}")
endif()
foreach(f IN LISTS core_files)
  file(READ "${f}" content)
  string(FIND "${content}" "raylib.h" pos)
  if(NOT pos EQUAL -1)
    message(FATAL_ERROR "${f} inclui raylib.h")
  endif()
endforeach()
message(STATUS "${n} arquivos de domino_core sem raylib.h")
